server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # These are for HTTP upstreams (NOT PHP-FPM)
    proxy_buffer_size 128k;
    proxy_buffers 64 128k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        fastcgi_connect_timeout 60s;
        fastcgi_send_timeout 600s;
        fastcgi_read_timeout 600s;

        # FastCGI buffer settings (for PHP-FPM)
        fastcgi_buffers 64 64k;
        fastcgi_buffer_size 128k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

    location ~ /\. {
        deny all;
    }

    location ~ ^/fpm-status$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        allow 127.0.0.1;
        deny all;
    }
}
