[supervisord]
nodaemon=true
user=root

[program:octane]
command=/usr/local/bin/php artisan octane:frankenphp --host=0.0.0.0 --port=80 --workers=4 --max-requests=500
directory=/var/www
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/octane.log
stderr_logfile=/var/log/octane-error.log

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/cron.log
stderr_logfile=/var/log/cron-error.log

[program:queue-worker]
command=/usr/local/bin/php artisan queue:work --tries=1 --timeout=370
directory=/var/www
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/log/queue-worker.log
stderr_logfile=/var/log/queue-worker-error.log
